export const Sport = {
  FOOTBALL: "FOOTBALL",
  FUTSAL: "FUTSAL",
  BASKETBALL: "BASKETBALL",
  VOLLEYBALL: "VOLLEYBALL",
  SWIMMING: "SWIMMING",
  TENNIS: "TENNIS",
  ATHLETICS: "ATHLETICS",
  RUGBY: "RUGBY",
  BOXING: "BOXING",
  WRESTLING: "WRESTLING",
  HOCKEY: "HOCKEY",
  BASEBALL: "BASEBALL",
  GOLF: "GOLF",
  CYCLING: "CYCLING",
  MARTIAL_ARTS: "MARTIAL_ARTS",
  AMERICAN_FOOTBALL: "AMERICAN_FOOTBALL",
} as const;

export type Sport = (typeof Sport)[keyof typeof Sport];


